### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by mkesper** [stamparm/fetch-some-proxies#1]
subprocess.Popen("timeout %d curl %s" % (TIMEOUT, IFCONFIG_URL), shell=True
This does not sound like a good idea to me, especially the shell=True part.

**Comment by stamparm** [comment]
So, basically, you are worried about a security issue where user provided data is not utilized/used. Can you please give me one good example of how this could be a security issue?

**Comment by stamparm** [comment]
https://docs.python.org/2/library/subprocess.html

![123](https://cloud.githubusercontent.com/assets/921555/19365336/90efed58-9192-11e6-8ae4-d709c4a2bc6f.png)

Can you please tell me what is an untrusted input in this case? Constant `TIMEOUT` and/or constant`IFCONFIG_URL`?

**Comment by mkesper** [comment]
OK, but why not simply use urllib and a timeout?

**Comment by stamparm** [comment]
Because `urllib2` doesn't support SOCKS proxies by default. `curl` does (available on all *nix systems). Introducing unnecessary third-party Python module for this is not an option.
