### ISSUE TITLE
Script is no longer returning usable proxies

### ISSUE THREAD

**Issue by Vanhal** [stamparm/fetch-some-proxies#10]
I've been using this script for a good few months now and it's been working great thanks.

But since 7-10 days ago it stop returning any usable proxies when it's run.
From looking at "fetch-some-list.txt" it seems as if the list is a lot smaller than it used to be, maybe some trouble with generating that list?

**Comment by stamparm** [comment]
Site from where list has been "scraped" got too strict. Now changed couple of things. This moment looks ok, but have to check in couple of days again.

Anyway, now it should work :)

**Comment by Vanhal** [comment]
Oh wow, yeah looks good right now.

**Comment by Vanhal** [comment]
This seems to be happening again now.

**Comment by stamparm** [comment]
"Patched" again. As said, problems with that site from where scraping is going on. If it continues I'll need to change it altogether. Sorry for trouble and thank you for reporting
