### ISSUE TITLE
Good script! Some questions and suggestions, perhaps?

### ISSUE THREAD

**Issue by BioFunker** [stamparm/fetch-some-proxies#11]
Excellent script.
I seem to be having an issue with getting results from certain countries.
Is there any way to define <s>the protocol</s>* and port? ie `--port="1080"`
Your script pulls from [here](https://raw.githubusercontent.com/stamparm/aux/master/fetch-some-list.txt ) and runs them against a predefined list of ip checking addresses.

<s>Looking a the list I find no socks5 protocol proxies - is this intentional?</s> **

I'm new to python and was looking for something very similar and your script is perfect to build upon.

The hassle of finding working proxies has definitely been reduced with your script - Thanks.

*, ** Upon closer examination of the script I found that `type` defines the protocol. Adding the `--type="socks5"` switch to the query, it did indeed filter the output accordingly.

Is there any way to check from a `live` proxy list such as the one [here](http://spys.one/en/socks-proxy-list/)?
Again, thanks! Just what I was looking for to help me get started!

**Comment by stamparm** [comment]
There are two reasons to not check "live" proxy lists from (this) program:

1) Those providers don't like to have automated scrappers (I already had problems with one of those). Hence, I am making periodic scrapping on my own from couple of (undisclosed) providers and put the list on that same `aux` repository you've already noticed
2) Each provider has its own format of displaying, hence there is no generic way how to make a scrapper out of user provided URL (if that was your intention)

Anyway, I could use that list you've provided (along with others) when I'll make a periodic update

**Comment by stamparm** [comment]
Just added (with the latest revision) option `--port`:

```
--port=PORT         List of ports for filtering (e.g. "1080,8000")
```

**Comment by stamparm** [comment]
Updated my "update" script to also include that site you've provided. Also, updated the `aux` script with items from there too (Note: I am filtering out those proxies which couldn't not be reached at the update phase - only a simple TCP connect test).

**Comment by Haseeb90** [comment]
How often do you update the list of proxies you have?

**Comment by stamparm** [comment]
@Haseeb90 around once a month (there is no need for frequent updates as proxy lists around are not so volatile)

**Comment by stamparm** [comment]
@Haseeb90 p.s. updated this moment
