### ISSUE TITLE
Bad IP geolocation

### ISSUE THREAD

**Issue by MMquant** [stamparm/fetch-some-proxies#12]
Just tested your script but it seems that some proxies in `fetch-some-list.txt` have bad countries along them. For example `http://185.93.3.123:8080` is in Czech Republic according to the `fetch-some-list.txt` but https://www.iplocation.net/ returns Spain, Madrid. How to do you discover geolocations for `fetch-some-list.txt`?

**Comment by stamparm** [comment]
Most probably somebody recently transferred the ownership. If you google around you'll see that `185.93.3.123` is frequently referred to be in Czech Republic (e.g. [here](https://bl.isx.fr/185.93.3.123), [here](https://www.stopforumspam.com/ipcheck/185.93.3.123), [here](https://www.proxynova.com/proxy-server-list/country-cz/), [here](http://www.gatherproxy.com/proxylist/country/?c=Czech%20Republic), etc.)

Geo-locations are parsed from public proxy lists. If they make a "mistake", then it will propagate to the list too. But, I wouldn't be too concerned as this same case proves that this was not a deliberate "mistake"
