### ISSUE TITLE
Error in line 245?

### ISSUE THREAD

**Issue by Henrietta1989** [stamparm/fetch-some-proxies#13]
I just downloaded fetch.py (Mac 10.14.2) and then run next line in Terminal and i always get same error:

python /Users/Henrietta/Downloads/fetch.py 

  File "/Users/Henrietta/Downloads/fetch.py", line 245
    main()
       ^
IndentationError: expected an indented block

**Comment by stamparm** [comment]
Unable to reproduce. You've most probably copy-pasted the source code from here (while whitespaces around `main()` got screwed). Please do "Save As..." of https://raw.githubusercontent.com/stamparm/fetch-some-proxies/master/fetch.py.
