### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by kuklofon** [stamparm/fetch-some-proxies#16]
`╭─uzz3r@linux-q1a4 ~/Pentest/fetch-some-proxies ‹master› 
╰─$ ./fetch.py 
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+
|f||e||t||c||h||-||s||o||m||e||-||p||r||o||x||i||e||s| <- v3.2.0
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+

[i] initial testing...
[i] retrieving list of proxies...
[!] something went wrong during the proxy list retrieval/parsing. Please check your network settings and try again
`
https://i.imgur.com/Yxp86St.png

**Comment by MEGALO-JOE** [comment]
Have you solved it? How to solve？Please tell me..

**Comment by stamparm** [comment]
@kuklofon @MEGALO-JOE please, update to the latest revision and retry. You should get an info what went wrong

**Comment by kuklofon** [comment]
Traceback (most recent call last):
  File "./fetch.py", line 279, in <module>
    main()
  File "./fetch.py", line 276, in main
    run()
  File "./fetch.py", line 156, in run
    content = retrieve(PROXY_LIST_URL, headers={"User-agent": USER_AGENT})
  File "./fetch.py", line 99, in retrieve
    return (retval or "").decode("utf8")
AttributeError: 'str' object has no attribute 'decode'
