### ISSUE TITLE
A 'curl not found' warning would be nice.

### ISSUE THREAD

**Issue by zxyufan** [stamparm/fetch-some-proxies#17]
I am running this fetch script in alpine linux (docker based), which is a lightweight system with only really necessary things, so it doesn't have **curl** by default. And the 'initial testing' in our fetch script uses **curl** to test a random 'ifconfig' target which ends up to failure of course because I don't have it, then fetch script discard all sock4/5 proxies. A warning here would be more user friendly I think.

**Comment by stamparm** [comment]
A) `socks` are automatically being discarded in case that `curl` is not available (disregard the whole `ifconfig` thing)
B) will do some warning message here

**Comment by stamparm** [comment]
Done

**Comment by zxyufan** [comment]
> Done

I didn't state my thoughts very clear in the original post, what I meant is that, without curl installed should not stop us make use of socks proxies. 

Thanks for this quick response and upgrade! Cheers!
