### ISSUE TITLE
something went wrong during the proxy list retrieval/parsing ('')

### ISSUE THREAD

**Issue by skalvin** [stamparm/fetch-some-proxies#23]
fetch.py
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+
|f||e||t||c||h||-||s||o||m||e||-||p||r||o||x||i||e||s| <- v3.2.3
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+

[i] initial testing...
[i] retrieving list of proxies...
[!] something went wrong during the proxy list retrieval/parsing (''). Please check your network settings and try again

**Comment by stamparm** [comment]
please update to the latest revision and retry:

![image](https://user-images.githubusercontent.com/921555/183645537-1f244d87-d39d-4291-a984-5695083579e6.png)
