### ISSUE TITLE
Socks on Windows

### ISSUE THREAD

**Issue by J0113** [stamparm/fetch-some-proxies#5]
Hi,
You said that socks are currently not supported by windows.
Are you planing on making it work on windows or is there any why to get it to work on windows?
Greetings Jolle!

**Comment by stamparm** [comment]
Steps to get it work on Windows too:

1) Update `fetch.py` to the latest revision (v2.63 this moment)
2) Get compiled `curl`  from one of providers at https://curl.haxx.se/download.html (e.g. https://winampplugins.co.uk/download.php?file=curl/curl_7_53_1_openssl_nghttp2_x64.7z <- this one worked at my side)
3) Extract `curl.exe` along with provided `ca-bundle.crt` to either directory where `fetch.py` resides or globally to `C:\Windows\System32`. Just run `curl.exe www.google.com` to make sure that it works in the first place (e.g. most probably if `ca-bundle.crt` is missing any kind of connection attempt will silently fail)
4) Run `fetch.py`

p.s.:
Content of `curl` package from `winampplugins.co.uk`:
![1](https://cloud.githubusercontent.com/assets/921555/24998557/d119d11e-203a-11e7-8532-960cb0839710.png)

Example run on Windows:
![2](https://cloud.githubusercontent.com/assets/921555/24998558/d11ad3e8-203a-11e7-9c0c-1b524cfbfc1b.png)
