### ISSUE TITLE
cant getting proxies

### ISSUE THREAD

**Issue by aburehan** [stamparm/fetch-some-proxies#7]
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+
|f||e||t||c||h||-||s||o||m||e||-||p||r||o||x||i||e||s| <- v2.64
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+

[i] initial testing...
[i] retrieving list of proxies...
[!]something went wrong during the proxy list retrieval/parsing. Please check your network settings and try again

**Comment by stamparm** [comment]
Yup. Noticed it yesterday. Problem is that hidester.com suddenly starts returning HTTP 500 when asked for the proxy list. I'll try to find a substitute

**Comment by aburehan** [comment]
oh ok waiting thanks for reply

**Comment by stamparm** [comment]
Told them via support email and they fixed it. Now everything works fine

**Comment by aburehan** [comment]
sir everything is fine now extracting proxies but dont know where txt file saving i mean where goes extracted proxies?

**Comment by stamparm** [comment]
```
$ python fetch.py -h
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+
|f||e||t||c||h||-||s||o||m||e||-||p||r||o||x||i||e||s| <- v2.64
+-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-++-+

Usage: fetch.py [options]

Options:
  --version           Show program's version number and exit
  -h, --help          Show this help message and exit
  --anonymity=ANON..  Regex for filtering anonymity (e.g. "anonymous|elite")
  --country=COUNTRY   Regex for filtering country (e.g. "china|brazil")
  --max-latency=MA..  Maximum (tolerable) latency in seconds (default 10)
  --output=OUTPUTF..  Store resulting proxies to output file
  --threads=THREADS   Number of scanning threads (default 10)
  --type=TYPE         Regex for filtering proxy type (e.g. "http")
```

Just use option `--output=...`

**Comment by aburehan** [comment]
i used C:\Users\Darknet\Desktop\New folder
and during scan i pressed cntrl+c  its aborted but none of text or proxies i got
the old one if we pressed for abort we got upper proxies in text file

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/27130474-64862924-50d4-11e7-8d13-a4f48afbcd96.png)

Expected behavior is shown at the upper picture. I believe that you are missing the point of "fetch-some-proxies". You are expecting the whole list, while this is absolutely not the point. This script filters out junk from the original list and writes results to the output file.

If you want a complete list please go to `https://hidester.com/proxydata/php/data.php?mykey=csv&gproxy=2`
