### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Oyetomi** [stamparm/fetch-some-proxies#8]
I keep getting this error " [i] initial testing...                                      [i] retrieving list of proxies...                           [!] something went wrong during the proxy list retrieval/parsing. Please check your network settings and try again      [Program finished]"

My connection is alright tho

**Comment by stamparm** [comment]
Hidester decided to ban retrieval of proxy list. Now negotiating with them to let me pull list every 24h. Fingers crossed

**Comment by Oyetomi** [comment]
Alright cool , thanks for the good work ,I appreciate it

**Comment by stamparm** [comment]
Fixed :). Switched to "private" list that I'll push to the Github at 24h basis (no more nagging from Hidester or similar). Everything stays the same (only the list's URL has been switched). Enjoy

**Comment by Oyetomi** [comment]
Gracias amigo :)
