### ISSUE TITLE
Doesn't save or anything

### ISSUE THREAD

**Issue by JosephShenton** [stamparm/fetch-some-proxies#9]
So i tried running this and it doesn't seem to work. Here is the output. There are no errors. No proxies. Nothing.
<img width="556" alt="screen shot 2018-01-09 at 12 28 02 pm" src="https://user-images.githubusercontent.com/12966231/34700726-a1dea8a6-f538-11e7-9241-0dc8b7154c6e.png">

**Comment by stamparm** [comment]
As there were no (usable) results, the resulting file `proxies.txt` is empty. You've restrained results to `--max-latency=2` while the tested single proxy from Australia has had bigger latency during testing.

You should expect only those proxies that pass the constraints into the resulting file.
